INSERT INTO MODEL (CATEGORY) VALUES ("Lightweight");
INSERT INTO MODEL (CATEGORY) VALUES ("Middleweight");
INSERT INTO MODEL (CATEGORY) VALUES ("Cruiserweight");
INSERT INTO MODEL (CATEGORY) VALUES ("Heavyweight");
COMMIT;