INSERT INTO STATE (STATUS) VALUES ("IDLE");
INSERT INTO STATE (STATUS) VALUES ("LOADING");
INSERT INTO STATE (STATUS) VALUES ("LOADED");
INSERT INTO STATE (STATUS) VALUES ("DELIVERING");
INSERT INTO STATE (STATUS) VALUES ("DELIVERED");
INSERT INTO STATE (STATUS) VALUES ("RETURNING");
COMMIT;